In [4]:
import numpy as np
np.__version__

'2.5.2'

In [7]:
new_list=[i for i in range(200)]
print(new_list)
my_list=list(filter(lambda num: num%10==0,new_list))
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199]
[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190]


In [7]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(a[-1])
a[0]

[1 2 3 4 5]
5


np.int64(1)

In [10]:
# Different ways to create an array using built in options

zeros_array=np.zeros(10,dtype=int)
print(zeros_array)


[0 0 0 0 0 0 0 0 0 0]


In [11]:
# In numpy we can create an array of n dimensions
# above array is 1d array
zeros_array.ndim

1

In [20]:
# 2D Array

array_2=np.zeros((3,4),dtype=int)
print(array_2)
print(array_2.ndim)
print(array_2.shape)
print(array_2.dtype)
print(array_2.size)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
2
(3, 4)
int64
12


#### Operations over an array/numpy array

In [48]:
b=np.arange(24)
# print(b)

# Convert an array from 1D to 2D 
b.resize(6,4)# Permanant
print(b)
# new_array=b.reshape(6,4)
# print(b)
# sum(b) # Column wise addition 
# print(sum(b.ravel())) # addition of all the numbers

# print(b.sum())
# print(b.sum(axis=1)) # row wise
# print(b.sum(axis=0)) # column wise

print(b.min())
print(b.max())
print(b.std())
print(b.mean(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
0
23
6.922186552431729
[ 1.5  5.5  9.5 13.5 17.5 21.5]


In [ ]:
# Convert nD to 1D

# one_D=b.ravel()
# print(b)
# print(one_D)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [56]:
# boolean_array=np.full((4,4),True)
# print(boolean_array)

new_array=np.full((4,4),1)
print(new_array)

new_array=np.zeros((4,4),dtype=bool)
print(new_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


In [59]:
# create an identity matrix

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
np.identity(5,dtype=bool)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [66]:
~np.identity(5,dtype=bool)

array([[False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])

In [67]:
b.diagonal()

array([ 0,  5, 10, 15])

In [68]:
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [75]:
# b[2][2]=-1
# print(b)

# b[3][1]=1
# b[3][2]=2
# b[4][1]=3
# b[4][2]=4
# print(b)

b[3:-1,1:-1]=[[1,2],[3,4]]
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 -1 11]
 [12  1  2 15]
 [16  3  4 19]
 [20 21 22 23]]


In [77]:
# access corner elements

print(b[::5,::3])


[[ 0  3]
 [20 23]]
